version: '3.8'

services:
  sftp-server:
    build: .
    container_name: time-ftp-server
    ports:
      - "8080:8080"
    volumes:
      - ./test-uploads:/app/test-uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    networks:
      - time-ftp-network

  web-server:
    image: nginx:alpine
    container_name: time-ftp-web
    ports:
      - "8090:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sftp-server
    networks:
      - time-ftp-network

networks:
  time-ftp-network:
    driver: bridge
