services:
  redis:
    image: redis:7-alpine
    container_name: csv-ftp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ftp-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csv-ftp-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_PATH=/app/data/database.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - ftp-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  ftp-network:
    driver: bridge