version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: csv-ftp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - ftp-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: csv-ftp-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_PATH=/app/data/database.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - ftp-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: csv-ftp-frontend
    ports:
      - "8100:80"
    depends_on:
      - backend
    networks:
      - ftp-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  ftp-network:
    driver: bridge