version: '3.8'

services:
  # バックエンドサービス
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ftp-manager-backend
    restart: unless-stopped
    ports:
      - "8091:8091"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
      - db-data:/app/database
    environment:
      - NODE_ENV=production
      - PORT=8091
      - DB_PATH=/app/database/ftp_manager.db
    networks:
      - ftp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # フロントエンドサービス
  frontend:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
    container_name: ftp-manager-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - ftp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # データベース管理用（オプション）
  adminer:
    image: adminer:latest
    container_name: ftp-manager-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    networks:
      - ftp-network
    profiles:
      - debug

networks:
  ftp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  db-data:
    driver: local